### ISSUE TITLE
CustomIdGenerator triggered even if already set via constructor

### ISSUE THREAD

**Issue by c33s** [ramsey/uuid-doctrine#81] opened 2019-06-24 17:36 UTC
i think its more a doctrine orm issue but thought it might be good to also report it here.

having a type class like that:

`Type.php`:
```php
    public function __construct(?string $name = null, UuidInterface $id = null)
    {
        $this->id = ($id ? $id : Uuid::uuid4());
        $this->name = $name;
    }
    /**
     * @var \Ramsey\Uuid\UuidInterface
     *
     * @ORM\Id
     * @ORM\Column(type="uuid", unique=true)
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class="Ramsey\Uuid\Doctrine\UuidGenerator")
     */
    protected $id;

    /**
     * @return UuidInterface
     */
    public function getId(): ?UuidInterface
    {
        return $this->id;
    }

    /**
     * @param UuidInterface $id
     *
     * @return self
     */
    public function setId(UuidInterface $id): self
    {
        $this->id = $id;

        return $this;
    }
   ...
```

having it integrated into symfony with doctrine and persisted via a command like that:
```php
    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $doctrine = $this->getContainer()->get('doctrine');
        $em = $doctrine->getManager();
        $type = new Type('my type3', null, Uuid::fromString('59ba2202-449a-462a-a8bd-013b38dd57be'));
        dump($type);
        $em->persist($type);
        dump($type);
       ...
```

in the first dump the uuid is correct `59ba2202-449a-462a-a8bd-013b38dd57be` but in the 2nd the autogenerator generates a new uuid.

**Comment by ramsey** [comment] 2019-06-24 22:09
I happened to notice this the other day, myself. I think the issue is because the generator isn't checking the entity to see whether it already has an ID set on it. 

See here:
https://github.com/ramsey/uuid-doctrine/blob/master/src/UuidGenerator.php#L22-L34

I'll go with that assumption and see if I can get a fix out for this. Thanks!

**Comment by TomasVotruba** [comment] 2019-07-12 07:59
This killed our day :cry: 

## Plug and Work Fix

```diff
 class Product
 {
     /**
      * @var UuidInterface
      * @ORM\Id
      * @ORM\Column(type="uuid_binary", unique=true)
      * @ORM\GeneratedValue(strategy="CUSTOM")
-     * @ORM\CustomIdGenerator(class="Ramsey\Uuid\Doctrine\UuidGenerator")
+     * @ORM\CustomIdGenerator(class="App\Doctrine\Uuid\RespectfulUuidGenerator")
      */
     private $id;
 }
```

And custom `UuidGenerator`:

```php
<?php declare(strict_types=1);

namespace App\Doctrine\Uuid;

use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Id\AbstractIdGenerator;
use Ramsey\Uuid\Uuid;
use Ramsey\Uuid\UuidInterface;
use ReflectionClass;
use ReflectionProperty;

/**
 * Fixes https://github.com/ramsey/uuid-doctrine/issues/81
 * @see \Ramsey\Uuid\Doctrine\UuidGenerator
 */
final class RespectfulUuidGenerator extends AbstractIdGenerator
{
    /**
     * @param object $entity
     * @return UuidInterface
     */
    public function generate(EntityManager $entityManager, $entity)
    {
        $idReflectionProperty = $this->findClassIdProperty($entity);
        if ($idReflectionProperty === null) {
            return Uuid::uuid4();
        }

        return $idReflectionProperty->getValue($entity) ?? Uuid::uuid4();
    }

    /**
     * @param object $object
     */
    private function findClassIdProperty($object): ?ReflectionProperty
    {
        $reflectionClass = new ReflectionClass($object);

        do {
            if ($reflectionClass->hasProperty('id')) {
                $idReflectionProperty = $reflectionClass->getProperty('id');
                $idReflectionProperty->setAccessible(true);

                return $idReflectionProperty;
            }
        } while ($reflectionClass = $reflectionClass->getParentClass());

        return null;
    }
}
``

**Comment by Ocramius** [comment] 2019-07-12 11:21
When using `@GeneratedValue`, the ORM operates under the assumption that:

 * new entities need a new ID
 * merged entities already have an ID

`@GeneratedValue` is not to be used in conjunction with assigned identifiers: that's by design.

**Comment by TomasVotruba** [comment] 2019-07-12 11:31
I know, it's an assumption that broke legacy project I work on.

**Comment by rendler-denis** [comment] 2020-03-16 09:43
Hello. I found this thread while searching for a cleaner solution to having predictable IDs for fixtures. I am using doctrine/doctrine-fixtures-bundle and having some entities with predictable IDs would help make the tests more clean. 
Would this be a good use-case for having fixed IDs @Ocramius ? 
An example would be end-to-end tests. In this case the only option I could think of right now is to call the API to create the entity (or create the entity directly into the DB if the case permits), fetch the entity from the DB, with the EntityManager, in order to get its ID, and then use the ID to call the API to fetch the entity for performing the assertions. 
Do you guys have a different solution? thanks.

**Comment by Ocramius** [comment] 2020-03-16 10:54
@rendler-denis look into UUID5 if you need stable IDs for fixtures

**Closed** 2020-04-25 19:44 UTC
